In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from findatapy.market import MarketDataGenerator, Market, MarketDataRequest
from dfconvert import df_store


def generate_market_data_for_tests():

    md_request = MarketDataRequest(start_date='01 Aug 2019', finish_date='07 Aug 2019', cut='NYC', category='fx',
                                   fields=['bid'], freq='tick', data_source='dukascopy',
                                   tickers=['EURUSD'])

    market = Market(market_data_generator=MarketDataGenerator())
    df = market.fetch_market(md_request)
    df.head()
    df_store('EURUSD_tick_2019_08_07.h5').store_df(df)

#generate_market_data_for_tests()

Ipython active
2019-08-08 15:22:46,439 - findatapy.market.datavendorweb - INFO - Request Dukascopy data
2019-08-08 15:22:46,482 - findatapy.market.datavendorweb - INFO - About to download from Dukascopy... for EURUSD
2019-08-08 15:22:47,006 - findatapy.market.datavendorweb - INFO - Downloading... 2019-08-01 00:00:00
2019-08-08 15:22:53,264 - findatapy.market.datavendorweb - INFO - Downloading... 2019-08-02 00:00:00
2019-08-08 15:23:00,527 - findatapy.market.datavendorweb - INFO - Downloading... 2019-08-03 00:00:00
2019-08-08 15:23:02,485 - findatapy.market.datavendorweb - INFO - Downloading... 2019-08-04 00:00:00
2019-08-08 15:23:04,616 - findatapy.market.datavendorweb - INFO - Downloading... 2019-08-05 00:00:00
2019-08-08 15:23:11,741 - findatapy.market.datavendorweb - INFO - Downloading... 2019-08-06 00:00:00
2019-08-08 15:23:18,952 - findatapy.market.datavendorweb - INFO - Completed request from Dukascopy
2019-08-08 15:23:21,022 - findatapy.market.ioengine - WARNING - Couldn't push MarketDataRequest_445__abstract_curve_key-None__alpha_vantage_api_key-x__category-fx__category_key-backtest_fx_dukascopy_tick_NYC_EURUSD__cut-NYC__data_source-dukascopy__environment-backtest__expiry_date-NaT__fields-bid__finish_date-2019-08-07 00:00:00__fred_api_key-x__freq-tick__freq_mult-1__gran_freq-None__quandl_api_key-x__resample-None__resample_how-last__start_date-2019-08-01 00:00:00__tickers-EURUSD__trade_side-trade__vendor_fields-None__vendor_tickers-None to Redis: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Storing h5: data\EURUSD_tick_2019_08_07.h5...
dataframe stored successfully

In [3]:
from dfconvert import df_store
df = df_store('EURUSD_tick_2019_08_07.h5').load_df()
df.head()

Loading h5: data\EURUSD_tick_2019_08_07.h5...
dataframe loaded successfully

                         EURUSD.bid
Date
2019-08-01 00:00:00.134     1.10715
2019-08-01 00:00:00.236     1.10715
2019-08-01 00:00:00.404     1.10716
2019-08-01 00:00:00.984     1.10716
2019-08-01 00:00:01.160     1.10717

In [4]:
len(df)

696466

In [5]:

def sampler(df, n):
    """
    e.g. for 1 in every 1000 ticks:
    df = sampler(df, 10000)
    """
    a = int(round(len(df)/n, 0))
    print(a)
    return df.sample(n= a)

In [6]:
df = sampler(df, 10)

69647

In [9]:
import structureforfinance

In [6]:
import numpy as np
import pandas as pd 
from datetime import datetime
import random as rd
from pandas import DataFrame

dates = DataFrame(pd.date_range(end=datetime.now(), periods=100, freq="d"), col)


start_price = 100
T = 1 
N = 100 
mu = 0.1
sigma = 0.1
S0 = 20
"""
dS=μS dt+σS dWt, t = time
n = no periods, mu = drift
sigma = stand dev,w = standard brownian motion 
S = geom standard brownian motion 
s0 = start price
"""   
N = dates.size
T = ((dates.max()-dates.min())/np.timedelta64(1,'D'))/ 365
dt = float(T)/N
t = np.linspace(0, T, N)
print(t)

[[0.        ]
 [0.00273973]
 [0.00547945]
 [0.00821918]
 [0.0109589 ]
 [0.01369863]
 [0.01643836]
 [0.01917808]
 [0.02191781]
 [0.02465753]
 [0.02739726]
 [0.03013699]
 [0.03287671]
 [0.03561644]
 [0.03835616]
 [0.04109589]
 [0.04383562]
 [0.04657534]
 [0.04931507]
 [0.05205479]
 [0.05479452]
 [0.05753425]
 [0.06027397]
 [0.0630137 ]
 [0.06575342]
 [0.06849315]
 [0.07123288]
 [0.0739726 ]
 [0.07671233]
 [0.07945205]
 [0.08219178]
 [0.08493151]
 [0.08767123]
 [0.09041096]
 [0.09315068]
 [0.09589041]
 [0.09863014]
 [0.10136986]
 [0.10410959]
 [0.10684932]
 [0.10958904]
 [0.11232877]
 [0.11506849]
 [0.11780822]
 [0.12054795]
 [0.12328767]
 [0.1260274 ]
 [0.12876712]
 [0.13150685]
 [0.13424658]
 [0.1369863 ]
 [0.13972603]
 [0.14246575]
 [0.14520548]
 [0.14794521]
 [0.15068493]
 [0.15342466]
 [0.15616438]
 [0.15890411]
 [0.16164384]
 [0.16438356]
 [0.16712329]
 [0.16986301]
 [0.17260274]
 [0.17534247]
 [0.17808219]
 [0.18082192]
 [0.18356164]
 [0.18630137]
 [0.1890411 ]
 [0.19178082]
 [0.19452055]
 [0.19726027]
 [0.2       ]
 [0.20273973]
 [0.20547945]
 [0.20821918]
 [0.2109589 ]
 [0.21369863]
 [0.21643836]
 [0.21917808]
 [0.22191781]
 [0.22465753]
 [0.22739726]
 [0.23013699]
 [0.23287671]
 [0.23561644]
 [0.23835616]
 [0.24109589]
 [0.24383562]
 [0.24657534]
 [0.24931507]
 [0.25205479]
 [0.25479452]
 [0.25753425]
 [0.26027397]
 [0.2630137 ]
 [0.26575342]
 [0.26849315]
 [0.27123288]]

In [8]:
W = np.random.standard_normal(size = N) 
W = np.cumsum(W)*np.sqrt(dt) ### standard brownian motion ###
W

array([ 0.00154657,  0.00165651,  0.10848022,  0.10878626,  0.04144905,
       -0.04775826, -0.10573756, -0.0721635 , -0.0180929 , -0.0677365 ,
       -0.05372459, -0.04202633,  0.04599959,  0.04340277, -0.02560094,
       -0.07373984, -0.03973841, -0.04811704, -0.05345294, -0.10076031,
       -0.10347908, -0.1024009 , -0.11222253, -0.00802347, -0.03580287,
       -0.00686374,  0.0349846 ,  0.07089457,  0.13107722,  0.17284755,
        0.04434128,  0.02004505, -0.01582446, -0.03701679, -0.05208501,
        0.01933715, -0.03530817,  0.02279699,  0.03102152,  0.01228667,
       -0.08668254, -0.02330552,  0.03519659,  0.06721592, -0.06057513,
       -0.02058906, -0.11275933, -0.05915551, -0.12768159, -0.14529606,
       -0.13090472, -0.15447105, -0.17438514, -0.23032055, -0.1930421 ,
       -0.17035062, -0.26226467, -0.17583579, -0.13929164, -0.11914266,
       -0.09452958, -0.13871145, -0.12975278, -0.13169511, -0.12603315,
       -0.06488586, -0.11367852, -0.15987395, -0.19501159, -0.25784488,
       -0.16724272, -0.23157803, -0.29701953, -0.33664394, -0.36986707,
       -0.35762779, -0.32445278, -0.29714106, -0.28830185, -0.28298859,
       -0.32255368, -0.33765955, -0.29323753, -0.33592339, -0.33993223,
       -0.34039723, -0.38955195, -0.37626766, -0.46515771, -0.45739945,
       -0.46260169, -0.51026966, -0.55407033, -0.60798535, -0.57470769,
       -0.53586228, -0.52916258, -0.6989836 , -0.70130251, -0.76430645])

In [31]:
W = W.reshape(100, 1)

In [32]:
W + t

array([[ 0.00154657],
       [ 0.00439623],
       [ 0.11395968],
       [ 0.11700544],
       [ 0.05240795],
       [-0.03405963],
       [-0.08929921],
       [-0.05298542],
       [ 0.00382491],
       [-0.04307897],
       [-0.02632733],
       [-0.01188934],
       [ 0.0788763 ],
       [ 0.07901921],
       [ 0.01275523],
       [-0.03264395],
       [ 0.0040972 ],
       [-0.0015417 ],
       [-0.00413788],
       [-0.04870552],
       [-0.04868456],
       [-0.04486665],
       [-0.05194855],
       [ 0.05499023],
       [ 0.02995055],
       [ 0.06162941],
       [ 0.10621748],
       [ 0.14486717],
       [ 0.20778955],
       [ 0.2522996 ],
       [ 0.12653306],
       [ 0.10497655],
       [ 0.07184678],
       [ 0.05339417],
       [ 0.04106568],
       [ 0.11522756],
       [ 0.06332197],
       [ 0.12416685],
       [ 0.13513111],
       [ 0.11913598],
       [ 0.0229065 ],
       [ 0.08902325],
       [ 0.15026508],
       [ 0.18502414],
       [ 0.05997281],
       [ 0.10269861],
       [ 0.01326807],
       [ 0.06961161],
       [ 0.00382526],
       [-0.01104949],
       [ 0.00608158],
       [-0.01474502],
       [-0.03191939],
       [-0.08511507],
       [-0.04509689],
       [-0.01966569],
       [-0.10884001],
       [-0.0196714 ],
       [ 0.01961247],
       [ 0.04250117],
       [ 0.06985398],
       [ 0.02841184],
       [ 0.04011024],
       [ 0.04090763],
       [ 0.04930931],
       [ 0.11319633],
       [ 0.0671434 ],
       [ 0.02368769],
       [-0.00871022],
       [-0.06880379],
       [ 0.0245381 ],
       [-0.03705749],
       [-0.09975926],
       [-0.13664394],
       [-0.16712735],
       [-0.15214834],
       [-0.1162336 ],
       [-0.08618215],
       [-0.07460322],
       [-0.06655024],
       [-0.1033756 ],
       [-0.11574174],
       [-0.06858   ],
       [-0.10852613],
       [-0.10979525],
       [-0.10752052],
       [-0.15393552],
       [-0.13791149],
       [-0.22406182],
       [-0.21356383],
       [-0.21602635],
       [-0.26095459],
       [-0.30201554],
       [-0.35319083],
       [-0.31717344],
       [-0.2755883 ],
       [-0.26614888],
       [-0.43323018],
       [-0.43280936],
       [-0.49307357]])

In [33]:
 #(mu-0.5*sigma**2)*
X=t + W ### ITO'S LEMMA
X

array([[ 0.00154657],
       [ 0.00439623],
       [ 0.11395968],
       [ 0.11700544],
       [ 0.05240795],
       [-0.03405963],
       [-0.08929921],
       [-0.05298542],
       [ 0.00382491],
       [-0.04307897],
       [-0.02632733],
       [-0.01188934],
       [ 0.0788763 ],
       [ 0.07901921],
       [ 0.01275523],
       [-0.03264395],
       [ 0.0040972 ],
       [-0.0015417 ],
       [-0.00413788],
       [-0.04870552],
       [-0.04868456],
       [-0.04486665],
       [-0.05194855],
       [ 0.05499023],
       [ 0.02995055],
       [ 0.06162941],
       [ 0.10621748],
       [ 0.14486717],
       [ 0.20778955],
       [ 0.2522996 ],
       [ 0.12653306],
       [ 0.10497655],
       [ 0.07184678],
       [ 0.05339417],
       [ 0.04106568],
       [ 0.11522756],
       [ 0.06332197],
       [ 0.12416685],
       [ 0.13513111],
       [ 0.11913598],
       [ 0.0229065 ],
       [ 0.08902325],
       [ 0.15026508],
       [ 0.18502414],
       [ 0.05997281],
       [ 0.10269861],
       [ 0.01326807],
       [ 0.06961161],
       [ 0.00382526],
       [-0.01104949],
       [ 0.00608158],
       [-0.01474502],
       [-0.03191939],
       [-0.08511507],
       [-0.04509689],
       [-0.01966569],
       [-0.10884001],
       [-0.0196714 ],
       [ 0.01961247],
       [ 0.04250117],
       [ 0.06985398],
       [ 0.02841184],
       [ 0.04011024],
       [ 0.04090763],
       [ 0.04930931],
       [ 0.11319633],
       [ 0.0671434 ],
       [ 0.02368769],
       [-0.00871022],
       [-0.06880379],
       [ 0.0245381 ],
       [-0.03705749],
       [-0.09975926],
       [-0.13664394],
       [-0.16712735],
       [-0.15214834],
       [-0.1162336 ],
       [-0.08618215],
       [-0.07460322],
       [-0.06655024],
       [-0.1033756 ],
       [-0.11574174],
       [-0.06858   ],
       [-0.10852613],
       [-0.10979525],
       [-0.10752052],
       [-0.15393552],
       [-0.13791149],
       [-0.22406182],
       [-0.21356383],
       [-0.21602635],
       [-0.26095459],
       [-0.30201554],
       [-0.35319083],
       [-0.31717344],
       [-0.2755883 ],
       [-0.26614888],
       [-0.43323018],
       [-0.43280936],
       [-0.49307357]])

In [37]:
S = np.exp(X)

In [38]:
S[0]

array([1.00154777])

In [39]:
df = dates.assign(bm = S)
df

                            0        bm
0  2019-05-02 13:37:26.238636  1.001548
1  2019-05-03 13:37:26.238636  1.004406
2  2019-05-04 13:37:26.238636  1.120707
3  2019-05-05 13:37:26.238636  1.124126
4  2019-05-06 13:37:26.238636  1.053806
5  2019-05-07 13:37:26.238636  0.966514
6  2019-05-08 13:37:26.238636  0.914572
7  2019-05-09 13:37:26.238636  0.948394
8  2019-05-10 13:37:26.238636  1.003832
9  2019-05-11 13:37:26.238636  0.957836
10 2019-05-12 13:37:26.238636  0.974016
11 2019-05-13 13:37:26.238636  0.988181
12 2019-05-14 13:37:26.238636  1.082070
13 2019-05-15 13:37:26.238636  1.082225
14 2019-05-16 13:37:26.238636  1.012837
15 2019-05-17 13:37:26.238636  0.967883
16 2019-05-18 13:37:26.238636  1.004106
17 2019-05-19 13:37:26.238636  0.998459
18 2019-05-20 13:37:26.238636  0.995871
19 2019-05-21 13:37:26.238636  0.952462
20 2019-05-22 13:37:26.238636  0.952482
21 2019-05-23 13:37:26.238636  0.956125
22 2019-05-24 13:37:26.238636  0.949378
23 2019-05-25 13:37:26.238636  1.056530
24 2019-05-26 13:37:26.238636  1.030404
25 2019-05-27 13:37:26.238636  1.063568
26 2019-05-28 13:37:26.238636  1.112064
27 2019-05-29 13:37:26.238636  1.155886
28 2019-05-30 13:37:26.238636  1.230954
29 2019-05-31 13:37:26.238636  1.286982
..                        ...       ...
70 2019-07-11 13:37:26.238636  1.024842
71 2019-07-12 13:37:26.238636  0.963621
72 2019-07-13 13:37:26.238636  0.905055
73 2019-07-14 13:37:26.238636  0.872281
74 2019-07-15 13:37:26.238636  0.846092
75 2019-07-16 13:37:26.238636  0.858861
76 2019-07-17 13:37:26.238636  0.890267
77 2019-07-18 13:37:26.238636  0.917427
78 2019-07-19 13:37:26.238636  0.928112
79 2019-07-20 13:37:26.238636  0.935616
80 2019-07-21 13:37:26.238636  0.901788
81 2019-07-22 13:37:26.238636  0.890705
82 2019-07-23 13:37:26.238636  0.933719
83 2019-07-24 13:37:26.238636  0.897155
84 2019-07-25 13:37:26.238636  0.896018
85 2019-07-26 13:37:26.238636  0.898058
86 2019-07-27 13:37:26.238636  0.857327
87 2019-07-28 13:37:26.238636  0.871176
88 2019-07-29 13:37:26.238636  0.799266
89 2019-07-30 13:37:26.238636  0.807701
90 2019-07-31 13:37:26.238636  0.805714
91 2019-08-01 13:37:26.238636  0.770316
92 2019-08-02 13:37:26.238636  0.739327
93 2019-08-03 13:37:26.238636  0.702443
94 2019-08-04 13:37:26.238636  0.728204
95 2019-08-05 13:37:26.238636  0.759125
96 2019-08-06 13:37:26.238636  0.766325
97 2019-08-07 13:37:26.238636  0.648411
98 2019-08-08 13:37:26.238636  0.648684
99 2019-08-09 13:37:26.238636  0.610746

[100 rows x 2 columns]

In [41]:
df.dtypes

0     datetime64[ns]
bm           float64
dtype: object

In [42]:
df.columns.values

array([0, 'bm'], dtype=object)